version: '3.8'

services:
  api:
    container_name: board-api
    image: node:14.17
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "800M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    working_dir: /home/node/api
    command: "yarn dev"
    ports:
      - 8180:8180
    volumes:
      - ./api:/home/node/api
      - images:/home/node/api/images
    depends_on:
      - mongo
    networks:
      - internal-nat

  web:
    container_name: board-web
    image: node:14.17
    working_dir: /home/node/web
    restart: unless-stopped
    command: "yarn dev"
    environment:
      - NODE_ENV=development
      - HOST=http://20.206.64.151
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/node/web
      - images:/home/node/web/public/img/uploads
    depends_on:
      - api
    networks:
      - internal-nat

  mongo:
    image: mongo:4.2.9
    container_name: board-mongo
    command: mongod --serviceExecutor adaptive
    restart: unless-stopped
    volumes:
      - ./db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: facing
      MONGO_INITDB_ROOT_PASSWORD: M0ng048
      MONGO_INITDB_DATABASE: board-facing
    networks:
      - internal-nat

networks:
  internal-nat:

volumes:
  images:
